### ISSUE TITLE
panel menu is very small in BlackMATE and Greybird

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/mate-themes#125]
There is a problem with the right-click menu on mate-panel in the BlackMATE and Greybird themes. The padding/margin appears to be far too thin:
![screenshot at 2016-06-20 00-21-28](https://cloud.githubusercontent.com/assets/729697/16180179/02a7da0c-367e-11e6-86f5-4ab19c47cbf1.png)
![screenshot at 2016-06-20 00-24-00](https://cloud.githubusercontent.com/assets/729697/16180180/02a8a07c-367e-11e6-9781-4cb989206157.png)
This does not occur in other themes (for example Menta):
![screenshot at 2016-06-20 00-24-39](https://cloud.githubusercontent.com/assets/729697/16180181/02aa9292-367e-11e6-91a6-b1be88caf433.png)

The issue is also present in most other MATE panel applets, but not in the main menubar (except for the right-click menu), the NetworkManager applet and the right-click menu on windows in the Window List applet.

Note: I have a Hi-DPI screen (IIRC 144dpi) where I've increased the text size to make everything appear normal. This affects the screenshots somewhat. I tested whether it affects the issue, and setting the font size as if I have a regular low-res (~96dpi) screen only makes things worse (the difference between BlackMATE/Greybird and other themes is even bigger).

Tested on Debian stretch, with gtk2.24.30 and gtk3.20.6. mate-panel version 1.14.1 and mate-themes 3.20.8.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-themes/commit/a66a87221cb6889f5bbd6ad87c5e52b1a6913fce
and associated commits to every BlackMATE version back to 3.14 should fix this. Tested in GTK 3.18 and GTK 3.21, covering the two theming syntaxes involved. Menus same as main menu for all panel menus with these.

This is assuming you are using a GTK3 panel, where a fix for another bug (panels spaced 1px from screen edge) caused some but not all panel menus to be very small, with 0px padding. I did not see that because although I maintain BlackMATE I normally work in my own "UbuntuStudio_Legacy" theme.

If you are running Debian's GTK 2 builds of mate this won't help as this fix is for a GTK 3 bug I accidently introduced. I have made no changes to BlackMATE GTK2 code and cannot test changes there due to not having a GTK 2 install.

**Comment by aykevl** [comment]
I edited `/usr/share/themes/BlackMATE/gtk-3.0/mate-applications.css` to apply the exact same changes, and the bug is fixed. Thank you!

Unfortunately, the issue is still present in Greybird (obviously, as it was not changed). I don't use Greybird, however, so as far as I'm concerned there's no issue anymore.

**Comment by raveit65** [comment]
> Unfortunately, the issue is still present in Greybird (obviously, as it was not changed). I don't use Greybird, however, so as far as I'm concerned there's no issue anymore.

:smile: greybird is from XFCE desktop........problem other people.

**Comment by lukefromdc** [comment]
You could look in the Greybird css for something that is setting padding to zero for those menus, using the BlackMATE changes as an example. If you find it and can fix it,  submit the change to the Greybird devs.

**Comment by aykevl** [comment]
In Debian Stretch, mate-themes depends on gtk2-engines-murrine, which recommends murrine-themes. That's the reason murrine-themes (with Greybird) is installed.

I doubt XFCE has been ported to gtk3.20, as they're still busy porting to GTK3 (3.14). Many other parts of the theme are broken and I don't use it anyway, so I won't bother fixing it.
http://blog.alteroot.org/articles/2016-04-12/road-to-xfce-4.14.html

**Comment by raveit65** [comment]
Poor debian.
See http://pkgs.fedoraproject.org/cgit/rpms/mate-themes.git/tree/mate-themes.spec#n45
I use gtk-murrine-engine as runtime require in fedora. If the package is splitted too in debian you should file out a debian report for it.
Mate-themes use only the engine from murrine as runtime require.

**Comment by lukefromdc** [comment]
Murrine is widely used in GTK2 as it can do all kinds of subtle gradients,
When I did the detail port of a modified UbuntuStudio to GTK3 as 
UbuntuStudio_Legacy I had to do one hell of a lot of work to duplicate
that in GTK3.  

"Recommends" are not dependencies in Debian, the package manage can
be set to pull them in or to ignore them.
