### ISSUE TITLE
BlackMATE and GreenLaguna have no grayed out (disabled) menu items

### ISSUE THREAD

**Issue by aykevl** [mate-desktop/mate-themes#139]
Disabled menu items don't show up as disabled (grayed out) in the BlackMATE and GreenLaguna themes in various applications using GTK3. For example, the "Versions..." menu item is not shown as grayed out while it is not clickable in the below screenshot (LibreOffice writer).

System: Debian stretch (testing)
GTK3 version: 3.21.5-3.
mate-themes version: 3.20.8-1 and master (aa7da1716)
MATE version: 1.14.1 (according to "About MATE")

![screenshot at 2016-09-12 18-30-27](https://cloud.githubusercontent.com/assets/729697/18443911/4ac23540-7917-11e6-83dd-034a4529223c.png)

I have the libreoffice-gtk3 package installed and it *looks* like this is GTK3 (there are animations), so I assume LibreOffice is using GTK3.
Update: it happens in many more applications using GTK3. GTK2 apps (e.g. Inkscape in Debian stretch) does not have this issue. E.g. it happens in mate-terminal, pluma, engrampa, meld, ...

This is also still an issue with the mate-panel right-click menu (outside widgets), see issue #125, which also looks like a menu so presumably has the same issue.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-themes/commit/16f0e3acab4cef9abdd3e1a0526d862d03bd9484
fixes this for BlackMATE in master and I also pushed equivalent commits for the GTK 3.22 and GTK 3.20 branches. Confirm this used to effect everything (not just libreoffice)

**Comment by aykevl** [comment]
Applying the same patch to `/usr/share/themes/BlackMATE/gtk-3.0/gtk-widgets.css` on my Debian installation fixes the issue. Thank you!
GreenLaguna isn't fixed yet, though, but I don't use that theme.

**Comment by lukefromdc** [comment]
Reopening as this still applied to GreenLaguna

**Comment by raveit65** [comment]
for GreenLaguna
4af9dc4857db472fccc2bb2d13b0f0db37014264

**Comment by lukefromdc** [comment]
I just sent a Debian package with these fixes to 
https://archive.org/details/DebianPackagesForMate-desktopWityGtk3AndCustomPanelTheme
